---
- name: Render {{ credential.id }} credential
  template:
    src: "create-credential.groovy"
    dest: "/tmp/jenkins-credentials/{{ credential.id }}.groovy"
    mode: 0440
    owner: jenkins
    group: jenkins
  register: credential_template_task

- name: Configure credential
  shell: >
    {{ jenkins_role_cli_command }} groovy = < "/tmp/jenkins-credentials/{{ credential.id }}.groovy"
  args:
    warn: no
  become: yes
  become_user: jenkins
  when:
    - credential_template_task.changed
    - ansible_virtualization_type != "docker"
