---

- name: "Install dependencies from yum"
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_role_yum_packages }}"

- name: "Install dependencies from pip"
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ jenkins_role_pip_packages }}"
