---

- name: Install Jenkins repository.
  yum_repository:
    name: Jenkins
    description: Jenkins YUM repo
    baseurl: http://pkg.jenkins.io/redhat-rc
    gpgkey: http://pkg.jenkins-ci.org/redhat-rc/jenkins-ci.org.key

#- name: Install Jenkins with Yum
#  command: yum -y install jenkins
#  become: true

- name: Install Jenkins from repository.
  package:
    name: jenkins-{{ jenkins_version }}
    state: installed


- name: Make sure Jenkins can write to the report directory.
  file:
    path: /var/lib/jenkins/reports
    owner: jenkins
    group: jenkins
    state: directory
    mode: 0755

- name: Ensure Jenkins runs on startup.
  service:
    name: jenkins
    enabled: yes
  notify:
    - wait for jenkins to start
