---

- set_fact:
   this_job_dir: "{{ jenkins_home }}/jobs/{{ job.name }}"
  tags:
    - jenkins-jobs
- set_fact:
   this_job_full_path: "{{ this_job_dir }}/config.xml"
  tags:
    - jenkins-jobs

- name: "Ensure {{ job.name }} {{ this_job_dir }} job folder exists"
  file:
    state: directory
    path: "{{ this_job_dir }}"
    owner: jenkins
    group: jenkins
    mode: 0775
  tags:
    - jenkins-jobs

- name: Render {{ job.name }} job xml
  template:
    src: "{{ job.template | default(template) }}"
    dest: "{{ this_job_full_path }}.template"
    owner: jenkins
    group: jenkins
  register: job_template_file
  tags:
    - jenkins-jobs

- name: Get mtime for job template file
  stat:
    path: "{{ this_job_full_path }}.template"
  register: statfile1
  tags:
    - jenkins-jobs

- name: Get mtime for job configuration file
  stat:
    path: "{{ this_job_full_path }}"
  register: statfile2
  tags:
    - jenkins-jobs

- name: Get information about {{ job.name }} Jenkins job
  shell: "{{ jenkins_role_cli_command }} list-jobs | grep -i ^{{ job.name }}$"
  failed_when: false
  register: infojob
  tags:
    - jenkins-jobs

- name: Show statfile1 for {{ job.name }} job
  debug:
    var: statfile1
  tags:
    - jenkins-jobs

- name: Show statfile2 for {{ job.name }} job
  debug:
    var: statfile2
  tags:
    - jenkins-jobs

- name: Show {{ job.name }} Jenkins job
  debug:
    var: infojob
  tags:
    - jenkins-jobs

- name: Create or update {{ job.name }} job
  shell: |
    if {{ jenkins_role_cli_command }} list-jobs | grep -i "^{{ job.name }}$"; then
      {{ jenkins_role_cli_command }} update-job {{ job.name }} < {{ this_job_full_path }}.template
    else
      {{ jenkins_role_cli_command }} create-job {{ job.name }} < {{ this_job_full_path }}.template
    fi
  become: yes
  become_user: jenkins
  when:
    - statfile2.stat.exists == false or statfile1.stat.mtime > statfile2.stat.mtime
    - ansible_virtualization_type != "docker"
  tags:
    - jenkins-jobs
