---

- name: Create pipeline jobs
  include: job.yml
  vars:
    template: "pipeline.xml.j2"
  loop_control:
    loop_var: job
  with_items:
    - "{{ pipeline_jobs }}"
  when: pipeline_jobs
  tags:
    - jenkins-jobs

- name: Create github folder jobs
  include: job.yml
  vars:
    template: "github-folder-multi-branch.xml.j2"
  loop_control:
    loop_var: job
  with_items:
    - "{{ github_folder_jobs }}"
  when: github_folder_jobs
  tags:
    - jenkins-jobs
