---

- name: Install Jenkins plugins.
  command: >
    {{ jenkins_role_cli_command }} install-plugin {{ item }}
    creates="{{ jenkins_home }}/plugins/{{ item }}.jpi"
  with_items: "{{ jenkins_plugins + jenkins_minimum_plugins }}"
  notify:
    - restart jenkins
    - wait for jenkins to start
  become: yes
  become_user: jenkins
  when: ansible_virtualization_type != "docker"

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
