---

- name: "Set proxy config for Jenkins"
  copy:
    src: "templates/proxy.xml.j2"
    dest: "{{ jenkins_home }}/proxy.xml"
    owner: jenkins
    group: jenkins
  notify:
    - restart jenkins
    - wait for jenkins to start
