---
- name: Jenkins startup wait
  shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
  register: result
  # until we get a 403 or (get a 200 ok and it has finished loading):
  until: (result.stdout.find("403 Forbidden") != -1) or ((result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1))
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  args:
    warn: no
