---
# safely restart jenkins
- name: restart jenkins
  command: >
    {{ jenkins_role_cli_command }} safe-restart
  become: yes
  become_user: jenkins
  listen: "restart jenkins"

- name: local restart jenkins
  service:
    name: jenkins
    state: restarted

- name: reload jenkins config
  command: >
    {{ jenkins_role_cli_command }} reload-configuration
  become: yes
  become_user: jenkins
  listen: "reload jenkins config"

  # updated this to wait 1 second if the service is still down
  # wait 5 seconds once it says it is up, so it can finish starting
  # otherwise strange issues were happening
- name: wait for jenkins to start
  shell: "curl --fail -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/ && sleep 10 || sleep 1"
  register: result
  # until we get a 403 or (get a 200 ok and it has finished loading):
  until: (result.stdout.find("403 Forbidden") != -1) or ((result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1))
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  args:
    warn: no
  listen: "wait for jenkins to start"

- name: configure default users
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  register: jenkins_users_config
  listen: "configure default users"
